<center>
  <img width="144" height="144" src="https://img.icons8.com/color/144/numpy.png" alt="numpy"></img>
  <h1 style="text-align: center;">NumPy</h1>
</center>

- Numpy is the fundamental package for scientific computing in python
- It has fast computation
- It provides a multidimentaional array objects
- An array is a grid of values and it contains inforamtion about the raw data

## Importance of Numpy
- wide variety of mathematical operations on array
- It supplies an enormous library of high level mathematical functions that operate on these arrays and matrices

## Installing NumPy

In [ ]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


## Importing NumPy

In [ ]:
import numpy as np

## Difference between NumPy Array and Python List

### Difference between NumPy Array and list
| Parameter | NumPy | List |
| -- | -- | -- |
| Data Type Storage | Can only store one type of data | Can store multiple types of data|
| Importing Module | Needs NumPy module to be installed and imported | No need of any library |
|Numerical Operations| Advanced and Efficient numerical operations | Less efficient and does not support advanced mathematical operations |
|Modification|Less modifications functions available|Offers a large variety of modification functions, hence makes it more easier to modify lists.|
|Memory Consumption|Consumes less memory|Consumes more memory|
|Computational Time|Fast|Slower|
|Convient|Convinent over large applications|Less convinent|

In [1]:
x = np.array([1,2,3,4])
print(x)
type(x)

NameError: ignored

In [ ]:
y = [1,2,3,4]
print(y)
type(y)

39.3 ns ± 1.18 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
[1, 2, 3, 4]


list

In [ ]:
%timeit [int(x) for x in range(0, 9)]

819 ns ± 21.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
%timeit np.arange(0,9)

499 ns ± 7.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)
print(arr2d.ndim)

# Error: The size of array should be same
# arrd = np.array([[1,2,3,4],[5,6,7,]])
# print(arrd)
# print(arrd.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
arr3d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr3d)
print(arr3d.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [ ]:
arr10d = np.array([1,2,3,4], ndmin=10)
print(arr10d)
print(arr10d.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Special Arrays

##### Zero Array

In [ ]:
arr_zero = np.zeros(4)
print(arr_zero)
arr_zero_3x4 = np.zeros((3,4))
print(arr_zero_3x4)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### Ones Array

In [ ]:
arr_ones = np.ones(4)
print(arr_ones)
arr_ones_3x4 = np.ones((3,4))
print(arr_ones_3x4)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


##### Empty Array

In [ ]:
arr_emp = np.empty(4)
print(arr_emp) # Gives an array with the values from memory

##### Range Array

In [ ]:
arr_rng = np.arange(4)
print(arr_rng)

[0 1 2 3]


##### Diagonal Array

In [ ]:
arr_sq_dia = np.eye(3)
print(arr_sq_dia)
arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


##### Linspace Array

In [ ]:
arr_lin = np.linspace(0, 20, num=5)
print(arr_lin)

[ 0.  5. 10. 15. 20.]


# Random Function

#### ```rand()``` function

In [ ]:
arr_rand_1d = np.random.rand(4)
print(arr_rand_1d)
arr_rand_1d = np.random.rand(4)
print(arr_rand_1d)

[0.62050328 0.76383121 0.65421931 0.32640226]
[0.06384331 0.92159461 0.50399012 0.91893324]


In [ ]:
arr_rand_2d = np.random.rand(2,3)
print(arr_rand_2d)

[[0.03203744 0.60671456 0.99845666]
 [0.11844872 0.697952   0.20354869]]


#### ```randn()``` function

Positive and Negative numbers close to zero

In [ ]:
arr_randn_1d = np.random.randn(4)
print(arr_randn_1d)

[ 0.94611662  1.36514092 -0.47836704  0.27513795]


#### ```ranf()``` function

Generates numbers from the interval [0, 1)

In [ ]:
arr_ranf_1d = np.random.ranf(4)
print(arr_ranf_1d)

[0.02904784 0.52193805 0.53373133 0.22038596]


#### ```ranf()``` function

Generates a random number between given range

In [ ]:
arr_randint_1d = np.random.randint(3, 9, 7) #(min, max, total_values)
print(arr_randint_1d)

[6 7 3 6 3 7 3]


## Datatypes in NumPy Array